### ISSUE TITLE
conf_dir needs to be writable

### ISSUE THREAD

**Issue by dylex** [neilmunday/slurm-mail#124]
**Versions**

OS version: Rocky Linux 8.9
Slurm version: 23.11.4
Slurm Mail version: 4.14

**Describe the bug**

Our slurmctld runs as non-root (`SlurmUser=slurm`, which is recommended), and we don't want to run slurm-mail as root either, so I changed /var/log/slurm-mail, /var/spool/slurm-mail, and the cron-job to the same owver, but it still complains that the configuration directory is not writable.  Why does this need to be writable?

**Logs**

```
ERROR:root:Error: /etc/slurm-mail is not writeable
Error: /etc/slurm-mail is not writeable
```

**Comment by neilmunday** [comment]
@dylex thanks for raising this issue. You are correct that `/etc/slurm-mail` does not need to be writeable by Slurm-Mail. The issue is due to the checks that the [check_dir](https://github.com/neilmunday/slurm-mail/blob/main/src/slurmmail/common.py#L41) function is performing.

I will fix this for version 4.15.

**Comment by dylex** [comment]
Great, thanks!

**Comment by neilmunday** [comment]
Slurm-Mail 4.15 has been released. Depending on how you have installed Slurm-Mail you can update like so:

```
dnf update slurm-mail
```

**Comment by neilmunday** [comment]
It should be noted that if you are not running Slurm-Mail as root, the ability for Slurm-Mail to include user's job output in e-mails will not work.
