### ISSUE TITLE
slurmctld dependency

### ISSUE THREAD

**Issue by langefa** [neilmunday/slurm-mail#49]
When installing slurm-mail with zypper on OpenSuse 15.3/15.4, the dependency `slurm-slurmctld` is not found:
```
# zypper install slurm-mail
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'slurm-slurmctld' needed by the to be installed slurm-mail-3.6-1.sl15.noarch
 Solution 1: do not install slurm-mail-3.6-1.sl15.noarch
 Solution 2: break slurm-mail-3.6-1.sl15.noarch by ignoring some of its dependencies
```
slurmctld is actually provided by the package `slurm`, see https://documentation.suse.com/sle-hpc/15-SP3/html/hpc-guide/cha-slurm.html. Similary, it looks like the correct package for Ubuntu is `slurmctld`.

**Comment by neilmunday** [comment]
Hi @langefa,

Thanks for reporting the issue with the SUSE RPM - I will look into this. I have been thinking that I should add to the integration tests the testing of OpenSUSE with the generated RPMs rather than just doing Rocky 8.

On the Ubuntu front, I have been looking at adding pre-built packages as part of version 4.0 of Slurm Mail which is currently under development. The `slurm-client` package is needed there as this provides the `sacct` and `scontrol` programs.

**Comment by neilmunday** [comment]
Fixed by commit https://github.com/neilmunday/slurm-mail/commit/7255ec718b289c3cdfcca4be78e154edd68dd2f3
